#201 - Reduce log level for unknown dependencies to debug to reduce l…
mojohaus/license-maven-plugin pull request #300
Opened 2019-02-27 06:45 UTC by ercpe

…og spam when using a shared missing file

https://github.com/mojohaus/license-maven-plugin/issues/201

2019-02-27 07:37 UTC, ppalaga requested changes
The proposed solution eliminates the warnings also for users that want to see them and I cannot accept it like this. I propose to solve the issue by adding a parameter much like we did in AbstractDownloadLicensesMojo
https://github.com/mojohaus/license-maven-plugin/blob/1a890f1f1e5911eaee23a4f79455ff482f449822/src/main/java/org/codehaus/mojo/license/AbstractDownloadLicensesMojo.java#L319-L333

I'd recommend to add your own ErrorRemedy-like enum that would initially contain just `warn` (default) and `ignore` so that you not need to implement the other options we have in AbstractDownloadLicensesMojo.

Do not forget to add an integration test.

2019-07-17 07:27 UTC, guidograzioli commented
I'm interested in this change, is anybody currently working on it? Happy to help otherwise

2020-02-26 17:38 UTC, ercpe commented on src/main/java/org/codehaus/mojo/license/AbstractAddThirdPartyMojo.java
> +     *   <ul>{@link UnkownFileRemedy#debug}: unkown files are logged debug</ul>
Typo throughout the change Unkown -> Unknown

2020-02-26 17:41 UTC, ercpe commented on src/main/java/org/codehaus/mojo/license/api/DefaultThirdPartyTool.java
> +                handleUnkownDependency(unkownFileRemedy,  "dependency [" + id + "] does not exist in project." );
Probably cleaner to hand `id` down to `handleUnkownDependency` instead of passing the log message around.

2020-03-03 13:23 UTC, wuwu2000 commented
postbuild integration tests seem to run not 100% stable -,.-

2020-03-04 11:13 UTC, wuwu2000 commented
can someone tell me why some builds fail randomly?

2020-07-16 14:28 UTC, wuwu2000 commented
@ppalaga Could you see why this jdk7 build fails please?

2026-08-12 19:48 UTC, closed without merging