Fix cookie header warning
mojohaus/license-maven-plugin pull request #408
Opened 2021-07-12 10:37 UTC by andrei-bamboi

https://github.com/mojohaus/license-maven-plugin/issues/403

2021-07-19 07:46 UTC, bmarwell requested changes

2021-07-19 07:46 UTC, bmarwell commented on src/main/java/org/codehaus/mojo/license/download/LicenseDownloader.java
> +        HttpClientBuilder clientBuilder = HttpClients.custom().setCookieSpec(CookieSpecs.STANDARD).setDefaultRequestConfig( configBuilder.build() );
There seems to be a missing import. Did you actually test-compile it locally?
Please run `mvn verify` locally.

2021-08-19 14:48 UTC, rmkellogg commented
I think the addition should be at line 101 on the configBuilder variable.  
`
 final Builder configBuilder = RequestConfig.copy( RequestConfig.DEFAULT ) //
                        .setConnectTimeout( connectTimeout ) //
                        .setSocketTimeout( socketTimeout ) //
                        **.setCookieSpec(CookieSpecs.STANDARD)**
                        .setConnectionRequestTimeout( connectionRequestTimeout );
`

Plus add the import of CookiesSpec.  Not tested on my end to resolve issue though.

2023-06-06 10:22 UTC, slawekjaranowski commented
Suppressed by #472 - @andrei-bamboi thanks for efforts

2023-06-06 10:22 UTC, closed without merging